//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Global Variables
int Menu1 = 0;
int Menu2 = 0;
int AutonChoice = -1;
int whichDriver = 0;
bool isPartner = true;
bool isMotorOn = false;
bool isClockwise = true;
//bool isLCDOn = false;
string string1;
string string2;
string string3;
string string4;

//constant LCD Button Numbers
const short NoButton = 0;
const short LButton = 1;
const short CButton = 2;
const short LCButton = 3;
const short RButton = 4;
const short LRButton = 5;
const short CRButton = 6;
const short AllButton = 7;

void waitForRelease1() {
	while (nLCDButtons != NoButton) {
		wait1Msec(10);
	}
}

void waitForRelease2() {
	while ((nLCDButtons2 == LButton || nLCDButtons2 == RButton) && nLCDButtons2 != CButton) {
		wait1Msec(10);
	}
}

void waitForPress1() {
	while (nLCDButtons == NoButton) {
		wait1Msec(10);
	}
}

void waitForPress2() {
	while (nLCDButtons2 == NoButton) {
	}
}

void centerText(int line, string stringToCenter) {
		//if ((stringLength % 2) == 0) {

		//}
		//else {

		//}
		vexLcdSetAt(line, (8-(strlen(stringToCenter) / 2)), stringToCenter);
}

bool sensorRangeCheck(tSensors thisSensor, int min, int max) {
	if (SensorValue[thisSensor] >= min && SensorValue[thisSensor] < max) {
		return true;
	}
	else {
		return false;
	}
}

void resetLimitMenu1(int menu1Min, int menu1Max) {
	if (Menu1 > menu1Max) {
		Menu1 = menu1Min;
	}
	//reset button if under limit
	else if (Menu1 < menu1Min) {
		Menu1 = menu1Max;
	}
}

void resetLimitMenu2(int menu2Min, int menu2Max) {
	if (Menu2 > menu2Max) {
		Menu2 = menu2Min;
	}
	//reset button if under limit
	else if (Menu2 < menu2Min) {
		Menu2 = menu2Max;
	}
}

void resetLimitLCDEncoder(int LCDEncoderMin, int LCDEncoderMax) {
	//LCD Encoder Reset above limit
	if (SensorValue[LCDEncoder] > LCDEncoderMax) {
		SensorValue[LCDEncoder] = LCDEncoderMin;
	}
	else if (SensorValue[LCDEncoder] < LCDEncoderMin) {
		SensorValue[LCDEncoder] =	LCDEncoderMax;
	}
}

void menu2Control() {
	//Menu2 navigation controls
	if (nLCDButtons2 == LButton) {
		while (nLCDButtons2 == LButton){
		}
		Menu2--;
		isMotorOn = false;
		SensorValue[LCDEncoder] = 0;
	}
	else if (nLCDButtons2 == RButton) {
		while (nLCDButtons2 == RButton){
		}
		Menu2++;
		isMotorOn = false;
		SensorValue[LCDEncoder] = 0;
	}
}

void menu1Control() {
	if (nLCDButtons == RButton) {
		Menu1++;
		isMotorOn = false;
		Menu2 = 0;
		SensorValue[LCDEncoder] = 0;
	}
	else if(nLCDButtons == LButton) {
		Menu1--;
		isMotorOn = false;
		Menu2 = 0;
		SensorValue[LCDEncoder] = 0;
	}
	waitForRelease1();
}

void motorDirectionControl() {

	if (SensorValue[lcdButton] == 0) {
	writeDebugStreamLine("switching");
		if (isClockwise) {
			isClockwise = false;
		}
		else {
			isClockwise = true;
		}
		while (SensorValue[lcdButton] == 0) {
		}
	}
}

void motorToggleControl() {
		if (nLCDButtons2 == CButton) {
		if (isMotorOn) {
			isMotorOn = false;
		}
		else {
			isMotorOn = true;
		}
		while (nLCDButtons2 == CButton) {
		}
	}
}

void runMotorFromLCD (tMotor _motor) {
	if (isMotorOn) {
		if (isClockwise) {
			motor[_motor] = SensorValue[LCDPotent] / 32.5;
		}
		else {
			motor[_motor] = -SensorValue[LCDPotent] / 32.5;
		}
	}
	else {
		motor[_motor] = 0;
	}
}


void autonSelection(int autonNumber) {
	if(nLCDButtons2 == CButton) {
		AutonChoice = autonNumber;
	}
	while (nLCDButtons2 == CButton) {
		wait1Msec(20);
	}
}

void changeDrivers() {
	if (nLCDButtons2 == CButton) {
		whichDriver = Menu2;
	}
}

void putPIDLCD(PID myPID) {
	if(sensorRangeCheck(LCDPotent, 0, 819)) {
		stringFormat(string1, "kP: %1.4f%c", myPID.kP);
		vexLcdSet(1, string1);
	}
	else if (sensorRangeCheck(LCDPotent, 819, 1638)) {
		stringFormat(string1, "kI: %1.4f%c", myPID.kI);
		vexLcdSet(1, string1);
	}
	else if (sensorRangeCheck(LCDPotent, 1638, 2457)) {
		stringFormat(string1, "kD: %1.4f%c", myPID.kD);
		vexLcdSet(1, string1);
	}
	else if (sensorRangeCheck(LCDPotent, 2457,3276)) {
		stringFormat(string1, "Error: %1.4f%c", myPID.error);
		vexLcdSet(1, string1);
	}
	else if (sensorRangeCheck(LCDPotent, 3276, 4500)) {
		stringFormat(string1, "Setpoint: %1.4f%c", myPID.setpoint);
		vexLcdSet(1, string1);
	}
	else {
		vexLcdSet(0, "Error");
		vexLcdSet(1, "Error");
	}
}
